### ISSUE TITLE
Online Tool Not Working in Your Own CS Machine

### ISSUE THREAD

**Issue by shloka-gondalia** [hajarhomayouni/DataQualityTestTool#7]
**Please look at the error file-**
[error.txt](https://github.com/hajarhomayouni/DataQualityTestTool/files/4678129/error.txt)

**Comment by hajarhomayouni** [comment]
Here were the steps that I took to get all of the R related errors to go away

1. Install R

-Sudo apt install r-base

2. Install cran stuff

-Sudo apt install r-cran-littler

-Sudo apt install r-cran-mvtnorm

3. Go into R and install oddstream

-devtools::install_github("pridiltal/oddstream")

**Comment by shloka-gondalia** [comment]
**The Solution which worked for me-**

[readme.txt](https://github.com/hajarhomayouni/DataQualityTestTool/files/4691045/readme.txt)

-Add h2o.jar to the dir

-Update paths in H2oRandomForest.py and H2oGradientBoosting.py

**-For tensorflow_core.keras error**
	-Activate the venv
	-pip uninstall tensorflow
	-pip install -Iv tensorflow==1.14.0 (It doesn't work for other version)

**-For pandas.core error**
	-Activate the venv
	-pip uninstall rpy2
	-pip install -Iv rpy2==3.2.7 (Other version gives C Stack Usage Error)

**-Other things to consider if there are still errors**

**-First**
	-Open R
	-install.packages("devtools")
	-devtools::install_github("pridiltal/oddstream")

**-Second**
	-Activate the venv
	-pip uninstall keras
	-pip install -Iv keras==2.2.5
